config/routes.rb
Rails.application.routes.draw do

  # default_url_options :host => "'http://localhost:3000"

  devise_for :users
  # match '/users/:id/destroy', to: 'users#destroy', via: [:get, :patch], as: 'signout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  # mount Ckeditor::Engine => '/ckeditor'
  
  resources :users
  root to:'users#index'
end

app/models/user.rb
class User < ApplicationRecord
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update


  belongs_to :role
  has_many   :user_projects
  has_many   :projects, through: :user_projects

  default_scope { order(:email) }


  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
            name: auth.extra.raw_info.name,
            #username: auth.info.nickname || auth.uid,
            email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
            password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  role_id                :integer
#  is_deleted             :boolean          default(FALSE)
#

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :finish_signup]
  before_action :authenticate_user!
  
  def index
    if admin?
      @users = User.all
    else
      redirect_to projects_path
    end
  end

  def edit
   @user   = User.find_by_id(params[:id])
    @roles = Role.all
  end

  def update_user
    @user           = User.find_by_id(params[:id])
    @user.email     = params[:user][:email]
    @user.role_id   = params[:user][:role_id]
    if @user.save
      flash[:success] = 'User successfully updated'
      redirect_to root_url
    else
      flash[:danger] = 'User already exist'
      redirect_to :back
    end
  end


  def update
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @user = User.new
    @roles = Role.all
  end

  def add_user
    @user = User.new
    password        = SecureRandom.hex(20)
    @user.email     = params[:user][:email]
    @user.password  = password
    @user.password_confirmation = password
    @user.role_id = params[:user][:role_id]
    @user.skip_confirmation!
    if @user.save
      @user.send_reset_password_instructions
      flash[:success] = 'User successfully saved'
      redirect_to root_url
    else
      flash[:danger] = 'User already exist'
      redirect_to :back
    end
  end


  def destroy
    # authorize! :delete, @user
    if @user.is_deleted == false
      @user.is_deleted = true
    else
      @user.is_deleted = false
    end
    @user.save!
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    accessible = [:name, :email] # extend with your own params
    accessible << [:password, :password_confirmation] unless params[:user][:password].blank?
    params.require(:user).permit(accessible)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
%h3 Edit User
%hr/
= form_for(@user, url: update_user_user_path(@user), method: 'put', :html => {:class => 'form-horizontal' }) do |f|
  .form-group
  %label.control-label.col-sm-2{:for => 'email'} Email:
  .col-sm-10
    = f.text_field :email, placeholder: 'email', style: 'width:30%;', class: 'form-control'
  .form-group
  %label.control-label.col-sm-2{:for => 'role'} Role:
  .col-sm-10
    = select_tag 'user[role_id]', options_for_select(@roles.collect {|p| [ p[:name], p[:id] ] }, :selected=>@user.role_id), class: 'form-control', style: 'width:30%;'
  .form-group
  %div{:style => 'margin-left: 18%;'}
    = f.submit 'Update', :class => 'btn btn-primary btn-sm'
    = link_to 'Back', users_path,:class => 'btn btn-default btn-sm'

app/views/users/finish_signup.html.haml
#add-email.container
  %h1 Add Email
  = form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f|
    - if @show_errors && current_user.errors.any?
      #error_explanation
        - current_user.errors.full_messages.each do |msg|
          = msg
          %br/
    .form-group
      = f.label :email
      .controls
        = f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Example: email@me.com'
        %p.help-block Please confirm your email address. No spam.
    .actions
      = f.submit 'Continue', :class => 'btn btn-primary'

app/views/users/index.html.haml
-#= link_to 'Create User', new_user_path, class: 'btn btn-primary btn-mini pull-right'
%br/
%br/
%div
  %table.table.table-striped.table-bordered.list-data-table{:cellspacing => "0", :width => "100%"}
    %thead
      %th Sr#
      %th Email
      %th User Type
      %th Created at
      %th Action
    %tbody
      - @users.each_with_index do |user,index|
        %tr
          %td= "#{index+1}"
          %td= "#{user.email}"
          %td= "#{user.role.name}"
          %td= "#{user.created_at}"
          %td
            = link_to 'Edit', edit_user_path(user)
            -#= link_to "Didn't receive confirmation instructions?", new_confirmation_path(user)
            -#= link_to 'Block', '#'
            - if user.is_deleted  == false
              = link_to 'Delete',user_path(user),  method: :delete, data: { confirm: 'Are you sure to delete user ?' }
            - else
              = link_to 'Undo',user_path(user),  method: :delete, data: { confirm: 'Are you sure to active this user ?' }
:javascript
  $(document).ready(function(){
      $('.list-data-table').DataTable({
        "pageLength": 50
       });
  })

app/views/users/new.html.haml
%h3 Create New User
%hr/
= simple_form_for @user, url: add_user_users_path, method: 'post', :html => {:class => 'form-horizontal' } do |f|
  .form-group
  %label.control-label.col-sm-2{:for => 'email'} Email:
  .col-sm-10
    = f.text_field :email, placeholder: 'email', style: 'width:30%;', class: 'form-control'
  .form-group
  %label.control-label.col-sm-2{:for => 'role'} Role:
  .col-sm-10
    = select_tag 'user[role_id]', options_for_select(@roles.collect {|p| [ p[:name], p[:id] ] }, 2), class: 'form-control', style: 'width: 30%;'
  .form-group
  %div{:style => 'margin-left: 18%;'}
    = f.submit 'Create', class: 'btn btn-primary btn-sm btn-round'

app/views/users/show.html.haml
%h1 oh i am loged in
%h6 its amazing
%li
  = link_to('Logout', destroy_user_session_path, :method => :delete)